version: '3'
services:
  dev:
    build: .
    volumes:
      - ./app:/home/bfx-cpp-api/app
    environment:
      - CMAKE_MAKE_PROGRAM=/usr/bin/cmake
      - CC=/usr/bin/clang
      - CXX=/usr/bin/clang++
    command: ["/sbin/entrypoint.sh"]
